{
 "title": "Keepconf",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(keepconf_enable, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hosts Status",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keepconf_bad{instance=\"$node\"}",
     "legendFormat": "BAD {{file}}"
    },
    {
     "expr": "keepconf_ok{instance=\"$node\"}",
     "legendFormat": "OK {{file}}"
    }
   ]
  },
  {
   "title": "Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "keepconf_fetch_time{instance=\"$node\"}",
     "legendFormat": "Fetch {{file}}"
    },
    {
     "expr": "keepconf_commit_time{instance=\"$node\"}",
     "legendFormat": "Commit {{file}}"
    }
   ]
  },
  {
   "title": "Total Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "keepconf_total_time{instance=\"$node\"}",
     "legendFormat": "{{file}}"
    }
   ]
  }
 ]
}