#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

keepconf_report -Indicate the status of keepconf execution

=head1 APPLICABLE SYSTEMS
Linux box with keepconf installed.

=head1 CONFIGURATION

[keepconf_*]
env.file /var/keepconf/keepconf-mon.csv

=head1 AUTHOR

Ricardo Fraile <rfrail3@yahoo.es>

=head1 VERSION
v.1.0.0

=head1 LICENSE

GPLv2

=head1 MAGICK MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh


if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title Keepconf report'
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_vlabel Hosts'
	echo 'graph_scale no'
	echo 'graph_category keepconf'
	echo 'graph_info Indicate the status of a keepconf execution.'

        echo "ok.label Ok"
        echo "ok.type GAUGE"
        echo "ok.min 0"

        echo "bad.label Bad"
        echo "bad.type GAUGE"
        echo "bad.min 0"

        echo "not.label Not Mon."
        echo "not.type GAUGE"
        echo "not.min 0"

	exit 0
fi

OK=`cat $file  | grep 'OK' | awk -F, '{print $2}' | tr -d '"'`
BAD=`cat $file  | grep 'BAD' | awk -F, '{print $2}' | tr -d '"'`
NOT=`cat $file  | grep 'NOT' | awk -F, '{print $2}' | tr -d '"'`



echo "ok.value `echo ${OK}`"
echo "bad.value `echo ${BAD}`"
echo "not.value `echo ${NOT}`"
